### ISSUE TITLE
Milestone 1 : specification / TODO list

### ISSUE THREAD

**Issue by matrefeytontias** [matrefeytontias/fourdee#1]
This is what needs to be done for the project to be considered viable.

- [x] Display a 4-cube (tesseract)
    - [x] Vector4 : holds 4D coordinates x, y, z, w
    - [x] Matrix5 : holds transformation for Vector4 objects (rotation, scale, shear, translation)
    - [x] Object4D : holds position, rotation, scale in 4D space
        - [x] Space4D : holds all other 4D objects to centralize projection and transformation
    - [x] Geometry4D : holds arrays of 4D vertices and faces
        - [x] BoxLinesGeometry4D : geometry for tesseract edges ; width, height, depth, duth
        - [x] BoxGeometry4D : geometry for solid tesseract ; idem
    - [x] Euler4D : represents **simple** rotation in 4D space : xy, xz, xw, yz, yw, zw, order (default "xyxzxwyzywzw")
    - [x] Proj4D : projects a 4D point onto 3D space
        - [x] OrthoProj : linear orthogonal projector
        - [x] StereoProj : stereographical projector

**Comment by matrefeytontias** [comment]
StereoProj is not necessary for this step to be complete.

**Comment by matrefeytontias** [comment]
Completed as of cf4b1e8113671a8766778371a71574f2b49abc45
