### ISSUE TITLE
Milestone 2 specification / TODO list

### ISSUE THREAD

**Issue by matrefeytontias** [matrefeytontias/fourdee#2]
Note : all collisions take place in 3D using the projections of the 4D objects. It doesn't matter if the object that is projected just in front of the character actually has w = 54645 and they have w = 0 ; they will still collide with it.

- [x] Have a character walk in a sample level ; proper camera movement and 4D rotation
    - [x] Level storage format
    - [X] Rotations : 3D camera using the mouse
        - [X] Pointer Lock 
    - [x] 4D XW or ZW rotation using two extra controls (not finished)
    - [x] Translations and jumps : 3D using the keyboard
        - [X] Translations
        - [x] Jumps
    - [x] Basic ground physics
    - [x] Basic player/object physics (triangle-based) (jumping on walls needs fixing)

**Comment by matrefeytontias** [comment]
Completed as of 391c3eae87a6be73e4c1dbbbf643be127be052b0
