### ISSUE TITLE
Milestone 3 specification / TODO list

### ISSUE THREAD

**Issue by cakedev0** [matrefeytontias/fourdee#3]
- [ ] Have some basic levels with simple mechanisms 
    - [X] Move game-related features out of Object4D into LevelObject
    - [X] Highlight selectable objects
    - [x] Switch to ThirdPersonControls on selection (and thus disable displacement and physics)
        - [x] Display the character's position in some way while that happens
    - [x] Linking of two LevelObject
    - [x] Restrict possible rotations of selectable objects
    - [ ] Create some visual representation of the dimension-travelling device 
    - [ ] Add goals to levels
    - [x] Improve physics' accuracy
